services:
  - type: web
    name: amazon-scraper
    env: python
    buildCommand: pip install -r amazon_scraper_project/backend/requirements.txt
    startCommand: python amazon_scraper_project/backend/main.py
    region: oregon
    plan: free
    branch: master
    runtime: python
